services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 210502
      MYSQL_USER: user
      MYSQL_PASSWORD: 210502
      MYSQL_DATABASE: stockmanagerdb
    ports:
      - "3307:3306"

  stock-manager:
    build: ./
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: 210502
      DB_NAME: stockmanagerdb
    ports:
      - "8080:8080"
