name: CI CD

on:
  push:
    branches:
     - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - uses: actions/setup-java@v4
      with:
         distribution: 'temurin'
         java-version: '17'
         cache: maven
    - name: Build Application .jar

      run: mvn clean package

    - name: Docker Compose Build

      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag stock-manager-stock-manager:latest ${{ secrets.DOCKER_USERNAME }}/stock-manager:${{ github.run_id }}
        
        docker push stock-manager-stock-manager:latest
        
        docker push ${{ secrets.DOCKER_USERNAME }}/stock-manager:${{ github.run_id }}
